### ISSUE TITLE
Error while compiling my modules with 17.09

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#2056]
> What version of ejabberd are you using?

Trying to install from source code, 17.09.

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

Source code

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have written my own modules which compiles with the version 16.03.92, however, now the same code does not compile with the version 17.09 neither with the 17.08.

The unique NO warning message that I can see in the ```make install``` log is:

```
include/mod_muc_room.hrl:95: type message() undefined
include/mod_muc_room.hrl:96: type presence() undefined
```

Have you any idea about what is crashing here? And why?

Thanks a lot!

**Comment by zinid** [comment]
This is because ejabberd internals have changed significantly starting from 16.12:
`jlib` "library" is not used anymore and is replaced by the [xmpp library](https://github.com/processone/xmpp).

**Comment by joanlopez** [comment]
So, what I have to change within my modules?

Replacing the include ```-include("jlib.hrl").``` by ```-include("xmpp.hrl").``` is enough?

Thanks a lot @zinid  =)

**Comment by zinid** [comment]
No, that's not enough of course. You need to change your code and in some cases a lot.

**Comment by joanlopez** [comment]
So, how I can know what changes (api usage) I have to do?

These are the modules (a bit modificated) I'm using in my Ejabberd instance:
- https://github.com/joanlopez/ejabberd-mod-apns/blob/master/src/mod_apns.erl
- https://github.com/joanlopez/ejabberd-mod-gcm/blob/master/src/mod_gcm.erl

Thanks a lot!

**Comment by joanlopez** [comment]
I'll replace these includes and then I'll try to fix all the compilation errors.

Do you think it is a good idea?

Is there any guide about the API changes appart from this blog post?
https://blog.process-one.net/ejabberd-16-12/

Thanks!!! :)

**Comment by zinid** [comment]
> These are the modules (a bit modificated) I'm using in my Ejabberd instance

Seems like your modules have lots of XML parsing, that means you need to rewrite a lot of code, for example, it's not allowed to use `fxml` module directly anymore, so every function call to this module should be rewritten.

**Comment by zinid** [comment]
> Is there any guide about the API changes appart from this blog post?

Listing changes doesn't make sense because *everything* has changed.
I've already given you a link to the xmpp library. You should start from there.

**Comment by joanlopez** [comment]
One more question:

- Appart from the xmpp library, can I keep the include and the calls to the ```jlib``` library like ```jlib:nameprep```? 

I've seen that this call, for example, is yet being used in the current ```muc_room.

Of course, I won't ask your to upgrade my modules, but, can you point me out the changes I have to do?

Appart from the direct calls to the ```fxml``` library, is there any other destacated thing to change?

Thanks a lot!

**Comment by joanlopez** [comment]
Finally it has compiled.

Unfortunately, it's crashing while starting. Like here: https://github.com/processone/ejabberd/issues/1158

Is there any other log where I can check what's happening?

Thanks!

**Comment by joanlopez** [comment]
Hi,

I've solved my last problem with the help from an answer in the corresponding blog post.

Thanks!
