### ISSUE TITLE
compile failed  with rebar_abort

### ISSUE THREAD

**Issue by lemon2015** [processone/ejabberd#2491]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

centos 7.5

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

when I try to build ejabberd 18.01 from the source ,  I install the gd lib from yum ,but it doesn't work.

```
yum install gd gd-devel
```
```
c_src/eimp.o: In function `transform':
/ejabberd-18.01/deps/eimp/c_src/eimp.c:281: undefined reference to `gdImageScale'
c_src/eimp.o: In function `decode':
/ejabberd-18.01/deps/eimp/c_src/eimp.c:181: undefined reference to `gdImageCreateFromWebpPtr'
c_src/eimp.o: In function `encode':
/ejabberd-18.01/deps/eimp/c_src/eimp.c:199: undefined reference to `gdImageWebpPtr'
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/eimp.o  -lwebp -lpng -ljpeg -lgd  -lpthread  -L"/usr/local/lib/erlang/lib/erl_interface-3.9.1/lib" -lerl_interface -lei -o priv/bin/eimp)
failed with return code 1 and the following output:
c_src/eimp.o: In function `transform':
/ejabberd-18.01/deps/eimp/c_src/eimp.c:281: undefined reference to `gdImageScale'
c_src/eimp.o: In function `decode':
/ejabberd-18.01/deps/eimp/c_src/eimp.c:181: undefined reference to `gdImageCreateFromWebpPtr'
c_src/eimp.o: In function `encode':
/ejabberd-18.01/deps/eimp/c_src/eimp.c:199: undefined reference to `gdImageWebpPtr'
collect2: error: ld returned 1 exit status

ERROR: compile failed while processing /ejabberd-18.01/deps/eimp: rebar_abort
make: *** [deps/.built] Error 1
```

**Comment by licaon-kter** [comment]
If you build... Why not build the latest version? :flushed:

**Comment by lemon2015** [comment]
@licaon-kter I want compile the mod_message_log separately for 18.01，because  we run the 18.01 online,but always failed ,so I  tried to recompile the whole project. (It works in 18.04).

**Comment by zinid** [comment]
You need to install libwebp-devel or how it's called on CentOS.
Or just compile ejabberd with `--disable-graphics` if you don't need to convert avatars between the image formats.

**Comment by lemon2015** [comment]
thanks！
