### ISSUE TITLE
Compilation error on Fedora Rawhide

### ISSUE THREAD

**Issue by bowlofeggs** [processone/ejabberd#2225]
Greetings!

I am working on packaging ejabberd 18.01 for Fedora Rawhide and Fedora 27, and I'm encountering a compilation error:

```
$ /usr/bin/rebar compile skip_deps=true -vv
…
Compiled src/nodetree_dag.erl                              
Compiled src/mod_version.erl 
Compiled src/mod_vcard_xupdate.erl                         
src/mod_vcard_sql.erl:63: unknown type specifier 'H'       
src/mod_vcard_sql.erl:195: unknown type specifier 'H'      
src/mod_vcard_sql.erl:207: unknown type specifier 'H'      
src/mod_vcard_sql.erl:32: function export/1 undefined      
src/mod_vcard_sql.erl:32: function get_vcard/2 undefined   
src/mod_vcard_sql.erl:32: function remove_user/2 undefined 
Compiling src/mod_vcard_sql.erl failed:                    
DEBUG: Worker compilation failed: {{error,                 
                                    {error,                
                                     [["src/mod_vcard_sql.erl:63: unknown type specifier 'H'\n",                      
                                       "src/mod_vcard_sql.erl:195: unknown type specifier 'H'\n",                     
                                       "src/mod_vcard_sql.erl:207: unknown type specifier 'H'\n"],                    
                                      ["src/mod_vcard_sql.erl:32: function export/1 undefined\n",                     
                                       "src/mod_vcard_sql.erl:32: function get_vcard/2 undefined\n",                  
                                       "src/mod_vcard_sql.erl:32: function remove_user/2 undefined\n"]],              
                                     []}},                 
                                   {source,"src/mod_vcard_sql.erl"}}                                                  
ERROR: compile failed while processing /home/rbarlow/rpmbuild/BUILD/ejabberd-18.01: rebar_abort
```

I'm not particularly familiar with Erlang enough to know for sure what the problem is. This is with Erlang 19.3.6.5. Let me know if I should provide more information!

**Comment by bowlofeggs** [comment]
Is the [H here](https://github.com/processone/ejabberd/blob/18.01/src/mod_vcard_sql.erl#L63-L64) some kind of string formatting/substitution thing?

```
	   ?SQL("select @(vcard)s from vcard"
                " where username=%(LUser)s and %(LServer)H")) of
```

/me goes to read about Erlang string formatting…

**Comment by prefiks** [comment]
This is defined in ejabberd_sql_pt.erl, most likelly your problem is from using ejabberd_sql_pt from older version of ejabberd (this flag was added recently), could you please check if ejabberd_sql_pt file is compiled before that failing file?

**Comment by bowlofeggs** [comment]
Hi @prefiks, thanks for the note. It helped me to realize that I had an older ejabberd installed on my dev box from an RPM while trying to compile it from source. When I removed that installation, it indeed builds!

Is there a way we can make the build ignore the installed version so this doesn't happen in the future? It's not a big deal because the official Fedora build system won't have ejabberd installed when compiling, but it might be nice for development. Feel free to close this if that's an impractical request, and thanks again!

**Comment by prefiks** [comment]
Unfortunately i don't know, when i seen report similar to yours i made sure that file is compiled as first thing, hoping that this will make compiler use what it compiled in first place instead of code loaded from other place. It seems this didn't help, and i have no other idea that may be used here, but will try to experiment a bit and maybe find something.

**Comment by cromain** [comment]
always run 'make distclean' first will ensure build env is clean from any previous build.
but this won't help if your build machine have ejabberd installed in standard erlang's lib (/usr/lib/erlang/lib/ejabberd) for example. only chance is to force build directory's ebin appended to erlang's path when rebar is calling compiler.
